# Generated by Django 5.0.3 on 2024-03-26 06:37

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "Stuck"), ("2", "Working"), ("3", "Done")],
                        default=1,
                        max_length=7,
                    ),
                ),
                (
                    "due",
                    models.CharField(
                        choices=[("1", "On Due"), ("2", "Overdue"), ("3", "Done")],
                        default=1,
                        max_length=7,
                    ),
                ),
            ],
            options={
                "ordering": ["project", "task_name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(blank=True, verbose_name="shortcut")),
                ("efforts", models.DurationField()),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "Stuck"), ("2", "Working"), ("3", "Done")],
                        default=1,
                        max_length=7,
                    ),
                ),
                ("dead_line", models.DateField()),
                (
                    "complete_per",
                    models.FloatField(
                        max_length=2,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("add_date", models.DateField(auto_now_add=True)),
                ("upd_date", models.DateField(auto_now=True)),
                ("assign", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
